settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: app
    path: .
    commands:
      install:
        status: true
        method: go build -o video-manager-go
      run:
        status: true
        method: /go/bin/dlv
    args:
      - exec
      - ./video-manager-go
      - --headless=true
      - --listen=:2345
      - --api-version=2
      - --accept-multiclient
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - .git
          - .realize
          - vendor
