version: "3.5"

services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/src/app
    command: realize start --run
    ports:
      - 8080:8080
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=video
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=default
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: